#pragma once

enum
{
    // Item identifiers
    // TODO: more

    IID_IRONSWORD = 0x01,
    IID_IRONBLADE,
    IID_STEELSWORD,
    IID_SILVERSWORD,

    IID_BINDINGBLADE = 0x0F,

    IID_IRONLANCE = 0x10,
    IID_STEELLANCE,
    IID_SILVERLANCE,

    IID_IRONAXE = 0x1B,
    IID_STEELAXE,
    IID_SILVERAXE,

    IID_IRONBOW = 0x27,
    IID_STEELBOW,
    IID_SILVERBOW,

    IID_BALLISTA = 0x30,
    IID_LONGBALLISTA,
    IID_KILLERBALLISTA,
    IID_FIRE = 0x33,

    IID_FIMBULVETR = 0x35,
    IID_ELFIRE = 0x36,

    IID_LIGHTNING = 0x3B,
    IID_DIVINE,

    IID_FLUX = 0x3F,

    IID_ECLIPSE = 0x41,

    IID_HEALSTAFF = 0x43,
    IID_MENDSTAFF,
    IID_RECOVERSTAFF,
    IID_PHYSICSTAFF,
    IID_FORTIFYSTAFF,
    IID_WARPSTAFF,
    IID_RESCUESTAFF,
    IID_RESTORESTAFF,
    IID_SILENCESTAFF,
    IID_SLEEPSTAFF,
    IID_TORCHSTAFF,
    IID_REPAIRSTAFF,

    IID_BERSERKSTAFF = 0x50,
    IID_UNLOCKSTAFF,
    IID_BARRIERSTAFF,

    IID_FIRESTONE = 0x53,
    IID_DIVINESTONE,
    IID_DEMONSTONE,

    IID_SKILLBOOSTER = 0x56,
    IID_LUCKBOOSTER,
    IID_HPBOOSTER,
    IID_DEFBOOSTER,
    IID_POWBOOSTER,
    IID_SPEEDBOOSTER,
    IID_RESBOOSTER,
    IID_MOVBOOSTER,
    IID_CONBOOSTER,

    IID_HEROCREST = 0x5F,
    IID_KNIGHTCREST,
    IID_ORIONBOLT,
    IID_ELYSIANWHIP,
    IID_GUIDINGRING,

    IID_CHESTKEY = 0x64,
    IID_DOORKEY,
    IID_BRIDGEKEY,
    IID_LOCKPICK,
    IID_VULNERARY,
    IID_ELIXIR,
    IID_PUREWATER,
    IID_TORCH,
    IID_ANTITOXIN,

    IID_MEMBERCARD = 0x6D,
    IID_SILVERCARD,

    IID_TINASTAFF = 0x76,
    IID_SAINTSTAFF,
};
