#pragma once

enum
{
    // map sprite ids

    UNITSPRITE_BALLISTA_REGULAR = 0x3F,
    UNITSPRITE_BALLISTA_LONG,
    UNITSPRITE_BALLISTA_KILLER,

    UNITSPRITE_42 = 0x42,
    UNITSPRITE_43,
    UNITSPRITE_44,
};
