
#pragma once

#include "gba/gba.h"

// TODO: move elsewhere
#define CHR_SIZE 0x20

enum
{
    BGCHR_TEXT_DEFAULT = 0x80,

    BGCHR_0_TEXT_POPUP = 0x100,

    BGCHR_DEBUGTEXT_DEFAULT = 0x2C0,

    BGCHR_LIMITVIEW = 0x280,

    BGCHR_ICON_BEGIN = 0x280,
    BGCHR_ICON_END   = 0x300,

    BGCHR_TILESET_A = 0x400,
    BGCHR_TILESET_B = 0x600,
};

enum
{
    BGPAL_DEBUGTEXT    = 0,
    BGPAL_TEXT_DEFAULT = 0,

    BGPAL_TALK         = 2,
    BGPAL_TALK_BUBBLE  = 3,
    BGPAL_ICONS        = 4, // .. 5
    BGPAL_LIMITVIEW    = 4, // .. 5
    BGPAL_TILESET      = 6, // .. 15
};

enum
{
    OBJCHR_SYSTEM_OBJECTS = 0x000,

    OBJCHR_DEBUGTEXT_DEFAULT = 0x180,

    OBJCHR_FACE_DEFAULT2 = 0x1E0,
    OBJCHR_FACE_DEFAULT1 = 0x268,
    OBJCHR_FACE_DEFAULT0 = 0x2F0,
    OBJCHR_FACE_DEFAULT3 = 0x378,
};

enum
{
    OBJPAL_SYSTEM_OBJECTS = 0,

    OBJPAL_FACE_DEFAULT0 = 6,
    OBJPAL_FACE_DEFAULT1 = 7,
    OBJPAL_FACE_DEFAULT2 = 8,
    OBJPAL_FACE_DEFAULT3 = 9,
};
