#pragma once

#include "common.h"
#include "menu.h"
#include "mapselect.h"

fu8 func_fe6_0801EA40(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 MapMenu_Suspend_Available(struct MenuEntInfo const * info, int id);
fu8 MapMenu_Suspend_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 MapMenu_End_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 MapMenu_Unit_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 MapMenu_Options_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 MapMenu_Status_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 func_fe6_0801EAE4(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 TutorialInterruptMenu_Continue_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 TutorialInterruptMenu_Quit_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitActionMenu_Wait_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 MapSelectActionReturnToUnitActionMenuWithCamera(struct MapSelectProc * proc, struct SelectTarget * target);
fu8 MapSelectActionReturnToUnitActionMenu(struct MapSelectProc * proc, struct SelectTarget * target);
fu8 MenuActionReturnToUnitActionMenu(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 RescueMapSelect_Help(struct MapSelectProc * proc, struct SelectTarget * target);
fu8 UnitActionMenu_Rescue_Available(struct MenuEntInfo const * info, int id);
fu8 UnitActionMenu_Rescue_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 RescueMapSelect_Select(struct MapSelectProc * proc, struct SelectTarget * target);
fu8 UnitActionMenu_Drop_Available(struct MenuEntInfo const * info, int id);
fu8 UnitActionMenu_Drop_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 DropRescueMapSelect_Select(struct MapSelectProc * proc, struct SelectTarget * target);
fu8 UnitActionMenu_Take_Available(struct MenuEntInfo const * info, int id);
fu8 UnitActionMenu_Take_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitActionMenu_Give_Available(struct MenuEntInfo const * info, int id);
fu8 UnitActionMenu_Give_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 TakeRescueMapSelect_Select(struct MapSelectProc * proc, struct SelectTarget * target);
fu8 GiveRescueMapSelect_Select(struct MapSelectProc * proc, struct SelectTarget * target);
fu8 UnitActionMenu_Attack_Available(struct MenuEntInfo const * info, int id);
fu8 UnitActionMenu_Attack_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitActionMenu_AttackBallista_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitActionMenu_AttackRegular_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitActionMenu_Attack_SwitchIn(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitActionMenu_Attack_SwitchOut(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitAttackItemMenu_Entry_Available(struct MenuEntInfo const * info, int id);
fu8 UnitAttackItemMenu_Entry_Select(struct MenuProc * menu, struct MenuEntProc * ent);
u32 UnitAttackItemMenu_Entry_Display(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitAttackItemMenu_Entry_SwitchIn(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitAttackItemMenu_Entry_SwitchOut(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 AttackMapSelect_Select(struct MapSelectProc * proc, struct SelectTarget * target);
fu8 AttackMapSelect_Cancel(struct MapSelectProc * proc, struct SelectTarget * target);
fu8 AttackMapSelect_SwitchIn(struct MapSelectProc * proc, struct SelectTarget * target);
u32 AttackMapSelect_End(struct MapSelectProc * proc);
fu8 AnyMenu_Trade_Available(struct MenuEntInfo const * info, int id);
fu8 UnitActionMenu_Trade_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 TradeMapSelect_Select(struct MapSelectProc * proc, struct SelectTarget * target);
fu8 UnitActionMenu_Seize_Available(struct MenuEntInfo const * info, int id);
fu8 UnitActionMenu_Seize_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitActionMenu_Visit_Available(struct MenuEntInfo const * info, int id);
fu8 UnitActionMenu_Visit_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitActionMenu_Play_Available(struct MenuEntInfo const * info, int id);
fu8 UnitActionMenu_Dance_Available(struct MenuEntInfo const * info, int id);
fu8 UnitActionMenu_Refresh_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 RefreshMapSelect_Select(struct MapSelectProc * proc, struct SelectTarget * target);
fu8 UnitActionMenu_Item_Available(struct MenuEntInfo const * info, int id);
fu8 UnitActionMenu_Item_Select(struct MenuProc * menu, struct MenuEntProc * ent);
u32 UnitItemMenu_Entry_Display(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitItemMenu_Entry_Available(struct MenuEntInfo const * info, int id);
fu8 UnitItemMenu_Entry_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 SingleItemMenu_Entry_SwitchIn(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 SingleItemMenu_Entry_SwitchOut(struct MenuProc * menu, struct MenuEntProc * ent);
void func_fe6_0801F854(int x, int y);
void UnitItemActionMenu_End(struct MenuProc * menu);
fu8 MenuActionReturnToUnitItemMenu(struct MenuProc * menu);
fu8 func_fe6_0801F8E0(struct MenuProc * menu);
fu8 func_fe6_0801F8F8(struct MenuProc * menu);
fu8 func_fe6_0801F948(struct MenuProc * menu);
fu8 UnitItemActionMenu_Use_Available(struct MenuEntInfo const * info, int id);
fu8 UnitItemActionMenu_Equip_Available(struct MenuEntInfo const * info, int id);
fu8 UnitItemActionMenu_Discard_Available(struct MenuEntInfo const * info, int id);
fu8 UnitItemActionMenu_Use_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitItemActionMenu_Equip_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitItemActionMenu_Trade_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitItemActionMenu_Discard_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitItemDiscardPromptMenu_Yes_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitAttackBallista_Entry_Available(struct MenuEntInfo const * info, int id);
u32 UnitAttackBallista_Entry_Display(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitAttackBallista_Entry_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitAttackBallista_Entry_SwitchIn(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitActionMenu_Staff_Available(struct MenuEntInfo const * info, int id);
fu8 UnitActionMenu_Staff_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitActionMenu_Staff_SwitchIn(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitActionMenu_Staff_SwitchOut(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitStaffItemMenu_Entry_Available(struct MenuEntInfo const * info, int id);
fu8 UnitStaffItemMenu_Entry_Select(struct MenuProc * menu, struct MenuEntProc * ent);
u32 UnitStaffItemMenu_Entry_Display(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitStaffItemMenu_Entry_SwitchIn(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitStaffItemMenu_Entry_SwitchOut(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitActionMenu_Talk_Available(struct MenuEntInfo const * info, int id);
fu8 UnitActionMenu_Talk_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 TalkMapSelect_Select(struct MapSelectProc * proc, struct SelectTarget * target);
fu8 UnitActionMenu_Support_Available(struct MenuEntInfo const * info, int id);
fu8 UnitActionMenu_Support_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 SupportMapSelect_Select(struct MapSelectProc * proc, struct SelectTarget * target);
fu8 UnitActionMenu_Door_Available(struct MenuEntInfo const * info, int id);
fu8 UnitActionMenu_Door_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitActionMenu_Chest_Available(struct MenuEntInfo const * info, int id);
fu8 UnitActionMenu_Chest_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitActionMenu_Supply_Available(struct MenuEntInfo const * info, int id);
fu8 UnitActionMenu_Supply_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitActionMenu_Armory_Available(struct MenuEntInfo const * info, int id);
fu8 UnitActionMenu_Armory_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitActionMenu_Vendor_Available(struct MenuEntInfo const * info, int id);
fu8 UnitActionMenu_Vendor_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitActionMenu_Secret_Available(struct MenuEntInfo const * info, int id);
fu8 UnitActionMenu_Secret_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitActionMenu_Arena_Available(struct MenuEntInfo const * info, int id);
fu8 UnitActionMenu_Arena_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 UnitActionMenu_Steal_Available(struct MenuEntInfo const * info, int id);
fu8 UnitActionMenu_Steal_Select(struct MenuProc * menu, struct MenuEntProc * ent);
void StealMapSelect_Init(struct MapSelectProc * proc);
fu8 StealMapSelect_SwitchIn(struct MapSelectProc * proc, struct SelectTarget * target);
fu8 StealMapSelect_Select(struct MapSelectProc * proc, struct SelectTarget * target);
fu8 StealItemMenu_Entry_Available(struct MenuEntInfo const * info, int id);
u32 StealItemMenu_Entry_Display(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 StealItemMenu_Entry_Select(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 MenuHelpBoxActiveUnitInventory(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 MenuHelpBoxTargetUnitInventory(struct MenuProc * menu, struct MenuEntProc * ent);
fu8 MenuHelpBoxActiveUnitBallista(struct MenuProc * menu, struct MenuEntProc * ent);
void HealMapSelect_Init(struct MapSelectProc * proc);
fu8 HealMapSelect_SwitchIn(struct MapSelectProc * proc, struct SelectTarget * target);
void RescueMapSelect_Init(struct MapSelectProc * proc);
fu8 RescueMapSelect_SwitchIn(struct MapSelectProc * proc, struct SelectTarget * target);
void DropRescueMapSelect_Init(struct MapSelectProc * proc);
void GiveRescueMapSelect_Init(struct MapSelectProc * proc);
fu8 GiveRescueMapSelect_SwitchIn(struct MapSelectProc * proc, struct SelectTarget * target);
void TakeRescueMapSelect_Init(struct MapSelectProc * proc);
fu8 TakeRescueMapSelect_SwitchIn(struct MapSelectProc * proc, struct SelectTarget * target);
void TradeMapSelect_Init(struct MapSelectProc * proc);
fu8 TradeMapSelect_SwitchIn(struct MapSelectProc * proc, struct SelectTarget * target);
void TalkMapSelect_Init(struct MapSelectProc * proc);
fu8 TalkMapSelect_SwitchIn(struct MapSelectProc * proc, struct SelectTarget * target);
void RefreshMapSelect_Init(struct MapSelectProc * proc);
fu8 RefreshMapSelect_SwitchIn(struct MapSelectProc * proc, struct SelectTarget * target);
void WarpUnitMapSelect_Init(struct MapSelectProc * proc);
fu8 WarpUnitMapSelect_SwitchIn(struct MapSelectProc * proc, struct SelectTarget * target);

SHOULD_BE_STATIC void func_fe6_0801EE4C(struct Unit * from, struct Unit * to);
