#include "gamedata.h"

#include "item.h"
#include "unit.h"
#include "support.h"

#include "constants/pids.h"
#include "constants/jids.h"
#include "constants/iids.h"
#include "constants/msg.h"
#include "constants/faces.h"
#include "constants/banim_pal.h"
#include "constants/unitsprites.h"
#include "constants/icons.h"
#include "constants/terrains.h"

#include "data/gamedata/pinfo.h"
#include "data/gamedata/jinfo.h"
#include "data/gamedata/iinfo.h"
#include "data/gamedata/terrain_info.h"
